#!/usr/bin/env python3
"""Rebuild the hole tally at the front of the shop pack from the sheets themselves.

Counting the drill list by hand goes stale the first time a schedule changes, and
silently - the table still looks right. So it is generated, and this script is the
only thing that writes it.

    python tools/build-hole-tally.py

It replaces whatever sits between the two TALLY markers in shop-pack.html.
"""
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PACK = os.path.join(HERE, '..', 'machine', 'drawings', 'shop-pack.html')

START = '<!-- TALLY:BEGIN - generated by tools/build-hole-tally.py, do not hand-edit -->'
END = '<!-- TALLY:END -->'

# (sheet, table index) -> (part, how many of that part get made).
# Sheet 2 carries four parts on one page, and its second table is the first one's
# plate drawn complete with the tongue - the same two plates, one also getting G1-G4.
PARTS = {
    ('s1a', 0): ('Front Y1 riser', 1),
    ('s1b', 0): ('Front Y2 riser', 1),
    ('s2', 0): ('X gantry end plate', 2),
    ('s2', 1): ('X gantry end plate, tongue', 1),
    ('s2', 2): ('Shelf bar', 2),
    ('s2', 3): ('Nut doubler block', 3),
    ('s3a', 0): ('X carriage plate', 1),
    ('s3b', 0): ('Z spacer bar', 2),
    ('s3c', 0): ('Z top stop block', 1),
    ('s3c', 1): ('Z top stop block', 1),
    ('s4', 0): ('Z plate', 1),
    ('s5', 0): ('Y nut sole bracket', 2),
    ('s6', 0): ('Interposer', 3),
    ('s7', 0): ('Rear plate', 1),
    ('s8', 0): ('Front joining strip', 3),
    ('s9', 0): ('Outboard plate', 2),
    ('s10', 0): ('X back joining plate', 1),
    ('s11', 0): ('X nut sole plate', 1),
}

# What each diameter is FOR. Keyed by diameter; the pack has one job per size.
PURPOSE = {
    '4.2': 'M5 tap drill &mdash; drilled through at the mill, <b>tapped at home</b>',
    '5.2': 'M5 clearance, <b>counterbore pilot</b> &mdash; stays 5.2 on 2a and 3a',
    '6': 'M5 clearance, <b>one size throughout</b> &middot; plus the three &oslash;6 hex-driver access holes',
    '6.8': 'M8 tap drill &mdash; drilled through, <b>tapped at home</b>',
    '9': 'M8 clearance &mdash; into extrusion T-nuts and beam corner bores, <b>float is wanted</b>',
    '22': 'The Z screw passes through the top stop block',
    '35': 'Encoder sensor bore',
}


def text_of(html):
    t = re.sub(r'<[^>]+>', '', html)
    t = re.sub(r'&#(\d+);', lambda m: chr(int(m.group(1))), t)
    for ent, ch in (('&ndash;', '-'), ('&mdash;', '-'), ('&nbsp;', ' '),
                    ('&times;', '*'), ('&oslash;', 'o'), ('&plusmn;', '+-')):
        t = t.replace(ent, ch)
    return ' '.join(t.split())


def collect(src):
    per_part, trip, unknown = {}, {}, []
    for name, blk in re.findall(r'<div class="plate pg-(s[0-9a-z]+)">(.*?)(?=\n<div class="plate )',
                                src, re.S):
        for ti, t in enumerate(re.findall(r'<table class="sched">(.*?)</table>', blk, re.S)):
            hdr = [text_of(x) for x in re.findall(r'<th[^>]*>(.*?)</th>', t, re.S)]
            dcol = hdr.index('o') if 'o' in hdr else None
            part, made = PARTS.get((name, ti), (None, 1))
            if part is None:
                unknown.append('%s table %d' % (name, ti))
                continue
            # sheet 2's second table repeats the first; only its new refs count
            skip = set()
            if (name, ti) == ('s2', 1):
                first = re.findall(r'<table class="sched">(.*?)</table>', blk, re.S)[0]
                skip = set(text_of(re.match(r'\s*<td[^>]*>(.*?)</td>', r, re.S).group(1))
                           for r in re.findall(r'<tr[^>]*>(.*?)</tr>', first, re.S)
                           if '<th' not in r and re.match(r'\s*<td', r, re.S))
            for r in re.findall(r'<tr[^>]*>(.*?)</tr>', t, re.S):
                if '<th' in r:
                    continue
                c = [text_of(x) for x in re.findall(r'<td[^>]*>(.*?)</td>', r, re.S)]
                if len(c) < 4 or dcol is None or len(c) <= dcol:
                    continue
                if c[0] in skip:
                    continue
                m = re.search(r'\d+', c[2].replace('4 * 7', '28'))
                n = int(m.group()) if m else 1
                dia = c[dcol].strip()
                if not re.match(r'^\d+(\.\d+)?$', dia):
                    continue      # the riser windows are cut-outs, not a drill size
                per_part[dia] = per_part.get(dia, 0) + n
                trip[dia] = trip.get(dia, 0) + n * made
    return per_part, trip, unknown


def render(per_part, trip):
    def key(d):
        try:
            return (0, float(d))
        except ValueError:
            return (1, d)

    out = [START,
           '<h3 style="margin-top:6mm">What gets drilled &mdash; the whole trip by drill size</h3>',
           '<p style="margin:0 0 .4rem;font-size:9.5pt"><b>Generated from the hole schedules</b> by '
           'tools/build-hole-tally.py, so it cannot drift from them. <b>Per part</b> is one piece; '
           '<b>on the trip</b> counts every piece that gets made.</p>',
           '<table class="sched">',
           '<tr><th>&oslash;</th><th class="d">Per part</th><th class="d">On the trip</th>'
           '<th>What it is for</th></tr>']
    tp = tt = 0
    for d in sorted(per_part, key=key):
        tp += per_part[d]
        tt += trip[d]
        label = '&oslash;' + d
        why = PURPOSE.get(d, '&#9888; <b>not described</b> &mdash; add it to tools/build-hole-tally.py')
        out.append('<tr><td><b>%s</b></td><td class="d">%d</td><td class="d"><b>%d</b></td><td>%s</td></tr>'
                   % (label, per_part[d], trip[d], why))
    out.append('<tr><td><b>TOTAL</b></td><td class="d"><b>%d</b></td><td class="d"><b>%d</b></td>'
               '<td>Window cut-outs are not holes and are not counted &mdash; there are two, '
               'one per riser</td></tr>' % (tp, tt))
    out.append('</table>')
    out.append(END)
    return '\n'.join(out)


def main():
    src = io.open(PACK, encoding='utf-8', newline='').read()
    nl = '\r\n' if '\r\n' in src else '\n'
    per_part, trip, unknown = collect(src)
    if unknown:
        print('schedules with no part mapping, NOT counted: %s' % ', '.join(unknown))
        return 1
    table = render(per_part, trip).replace('\n', nl)

    if START in src and END in src:
        lo = src.index(START)
        hi = src.index(END) + len(END)
        src = src[:lo] + table + src[hi:]
    else:
        anchor = '<p style="margin:0 0 .35rem"><b>Sheets that exist and are drawable</b>'
        if anchor not in src:
            print('cannot find where to put the tally')
            return 1
        src = src.replace(anchor, table + nl + nl + anchor, 1)
    io.open(PACK, 'w', encoding='utf-8', newline='').write(src)

    print('%d sizes, %d holes per part, %d on the trip'
          % (len(per_part), sum(per_part.values()), sum(trip.values())))
    return 0


if __name__ == '__main__':
    sys.exit(main())
